from typing import List
from backend.app.domain.models.network import Node, Edge, NodeType, EdgeType

# Seed nodes representing an expanded critical infrastructure and community resilience network (33 nodes)
SEED_NODES: List[Node] = [
    # --- PATH A: MAIN TAIWAN-BELGIUM-MUNICH SYSTEM ---
    Node(
        id="supplier-silicon",
        name="Hsinchu Advanced Materials Depot",
        type=NodeType.SUPPLIER,
        location="Hsinchu, Taiwan",
        latitude=24.78,
        longitude=120.99,
        base_cost=15000.0,
        capacity=200.0,
        health=1.0,
        risk_score=0.0,
        inventory=500.0,
        safety_stock=200.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"material": "Refined Silicon Wafers", "partner_tier": 2}
    ),
    Node(
        id="factory-wafer",
        name="Taichung Precision Sourcing Fab",
        type=NodeType.FACTORY,
        location="Taichung, Taiwan",
        latitude=24.14,
        longitude=120.67,
        base_cost=45000.0,
        capacity=100.0,
        health=1.0,
        risk_score=0.0,
        inventory=150.0,
        safety_stock=60.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"material": "Advanced Component Blocks", "ops_tier": 1}
    ),
    Node(
        id="port-kaohsiung",
        name="Port of Kaohsiung Transit Hub",
        type=NodeType.PORT,
        location="Kaohsiung, Taiwan",
        latitude=22.62,
        longitude=120.30,
        base_cost=25000.0,
        capacity=800.0,
        health=1.0,
        risk_score=0.0,
        inventory=400.0,
        safety_stock=100.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"terminal_ops": "Container Terminal 4"}
    ),
    Node(
        id="port-antwerp",
        name="Port of Antwerp Emergency Gateway",
        type=NodeType.PORT,
        location="Antwerp, Belgium",
        latitude=51.21,
        longitude=4.40,
        base_cost=30000.0,
        capacity=600.0,
        health=1.0,
        risk_score=0.0,
        inventory=300.0,
        safety_stock=120.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"terminal_ops": "Europa Terminal"}
    ),
    Node(
        id="port-rotterdam",
        name="Port of Rotterdam Alternative Terminal",
        type=NodeType.PORT,
        location="Rotterdam, Netherlands",
        latitude=51.92,
        longitude=4.47,
        base_cost=32000.0,
        capacity=700.0,
        health=1.0,
        risk_score=0.0,
        inventory=300.0,
        safety_stock=100.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"terminal_ops": "ECT Delta Terminal"}
    ),
    Node(
        id="warehouse-munich",
        name="Munich Regional Logistics Hub",
        type=NodeType.WAREHOUSE,
        location="Munich, Germany",
        latitude=48.13,
        longitude=11.58,
        base_cost=10000.0,
        capacity=400.0,
        health=1.0,
        risk_score=0.0,
        inventory=160.0,
        safety_stock=80.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"safety_buffer_days": 4}
    ),
    Node(
        id="factory-assembly",
        name="Munich Essential Operations Center",
        type=NodeType.FACTORY,
        location="Munich, Germany",
        latitude=48.136,
        longitude=11.583,
        base_cost=85000.0,
        capacity=100.0,
        health=1.0,
        risk_score=0.0,
        inventory=80.0,
        safety_stock=40.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"assembly_resource": "Critical Resource Modules"}
    ),
    Node(
        id="distributor-europe",
        name="Frankfurt Emergency Distribution Center",
        type=NodeType.DISTRIBUTION_CENTER,
        location="Frankfurt, Germany",
        latitude=50.11,
        longitude=8.68,
        base_cost=18000.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"region": "Western Europe"}
    ),
    Node(
        id="product-nexus-ecu",
        name="Emergency Supply Resource Units",
        type=NodeType.PRODUCT,
        location="European Sector",
        latitude=52.52,
        longitude=13.40,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=50.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"unit_equivalent_value": 2500.0}
    ),

    # --- PATH B: JAPAN-GERMANY-STUTTGART PIPELINE ---
    Node(
        id="supplier-silicon-jp",
        name="Tokyo Strategic Resource Partner",
        type=NodeType.SUPPLIER,
        location="Tokyo, Japan",
        latitude=35.67,
        longitude=139.65,
        base_cost=16000.0,
        capacity=200.0,
        health=1.0,
        risk_score=0.0,
        inventory=500.0,
        safety_stock=200.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"material": "Specialized Compounds", "partner_tier": 2}
    ),
    Node(
        id="factory-wafer-jp",
        name="Kumamoto Precision Assembly Plant",
        type=NodeType.FACTORY,
        location="Kumamoto, Japan",
        latitude=32.78,
        longitude=130.72,
        base_cost=47000.0,
        capacity=100.0,
        health=1.0,
        risk_score=0.0,
        inventory=150.0,
        safety_stock=60.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"material": "Medical Sourcing Circuits", "ops_tier": 1}
    ),
    Node(
        id="port-yokohama",
        name="Port of Yokohama Transit Hub",
        type=NodeType.PORT,
        location="Yokohama, Japan",
        latitude=35.44,
        longitude=139.64,
        base_cost=26000.0,
        capacity=800.0,
        health=1.0,
        risk_score=0.0,
        inventory=400.0,
        safety_stock=100.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"terminal_ops": "Minato Mirai Pier"}
    ),
    Node(
        id="port-hamburg",
        name="Port of Hamburg Emergency Gateway",
        type=NodeType.PORT,
        location="Hamburg, Germany",
        latitude=53.54,
        longitude=9.98,
        base_cost=31000.0,
        capacity=600.0,
        health=1.0,
        risk_score=0.0,
        inventory=300.0,
        safety_stock=120.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"terminal_ops": "Burchardkai Terminal"}
    ),
    Node(
        id="warehouse-stuttgart",
        name="Stuttgart Regional Logistics Hub",
        type=NodeType.WAREHOUSE,
        location="Stuttgart, Germany",
        latitude=48.77,
        longitude=9.18,
        base_cost=11000.0,
        capacity=400.0,
        health=1.0,
        risk_score=0.0,
        inventory=160.0,
        safety_stock=80.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"safety_buffer_days": 4}
    ),
    Node(
        id="factory-assembly-stuttgart",
        name="Stuttgart Essential Operations Center",
        type=NodeType.FACTORY,
        location="Stuttgart, Germany",
        latitude=48.78,
        longitude=9.19,
        base_cost=86000.0,
        capacity=100.0,
        health=1.0,
        risk_score=0.0,
        inventory=80.0,
        safety_stock=40.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"assembly_resource": "Advanced Disaster-Response Kits"}
    ),
    Node(
        id="distributor-europe-stuttgart",
        name="Stuttgart Emergency Distribution Center",
        type=NodeType.DISTRIBUTION_CENTER,
        location="Stuttgart, Germany",
        latitude=48.79,
        longitude=9.20,
        base_cost=19000.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"region": "Central Europe"}
    ),
    Node(
        id="product-nexus-ecu-pro",
        name="Emergency Response Units Pro",
        type=NodeType.PRODUCT,
        location="Global Pro Market",
        latitude=52.52,
        longitude=13.41,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=50.0,
        daily_consumption=40.0,
        replenishment_rate=40.0,
        metadata={"unit_equivalent_value": 3200.0}
    ),

    # --- STANDBY ALTERNATIVES & BACKUP DEPOTS ---
    Node(
        id="supplier-silicon-de",
        name="Burghausen Strategic Materials Partner",
        type=NodeType.SUPPLIER,
        location="Burghausen, Germany",
        latitude=48.17,
        longitude=12.83,
        base_cost=18000.0,
        capacity=150.0,
        health=1.0,
        risk_score=0.0,
        inventory=300.0,
        safety_stock=100.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"material": "Raw Sourcing Reserves", "partner_tier": 2}
    ),
    Node(
        id="factory-wafer-de",
        name="Dresden Advanced Operations Center",
        type=NodeType.FACTORY,
        location="Dresden, Germany",
        latitude=51.05,
        longitude=13.73,
        base_cost=49000.0,
        capacity=100.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=45.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"material": "Alternative Component Assembly", "ops_tier": 1}
    ),
    Node(
        id="port-shanghai",
        name="Port of Shanghai Gateway",
        type=NodeType.PORT,
        location="Shanghai, China",
        latitude=31.23,
        longitude=121.47,
        base_cost=27000.0,
        capacity=900.0,
        health=1.0,
        risk_score=0.0,
        inventory=400.0,
        safety_stock=100.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"terminal_ops": "Yangshan Deepwater Port"}
    ),
    Node(
        id="warehouse-frankfurt",
        name="Frankfurt Strategic Reserve Hub",
        type=NodeType.WAREHOUSE,
        location="Frankfurt, Germany",
        latitude=50.12,
        longitude=8.69,
        base_cost=12000.0,
        capacity=300.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"safety_buffer_days": 3}
    ),

    # --- COMMUNITY RECIPIENTS & EMERGENCIES ---
    Node(
        id="customer-bmw",
        name="Munich Regional Hospital Network",
        type=NodeType.PRODUCT,
        location="Munich, Germany",
        latitude=48.177,
        longitude=11.556,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=20.0,
        replenishment_rate=20.0,
        metadata={"sector": "Critical Public Health"}
    ),
    Node(
        id="customer-audi",
        name="Bavarian Public Health Distribution",
        type=NodeType.PRODUCT,
        location="Ingolstadt, Germany",
        latitude=48.782,
        longitude=11.416,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=20.0,
        replenishment_rate=20.0,
        metadata={"sector": "Emergency Medical Logistics"}
    ),
    Node(
        id="customer-mercedes",
        name="Stuttgart Disaster Relief Coordination",
        type=NodeType.PRODUCT,
        location="Stuttgart, Germany",
        latitude=48.790,
        longitude=9.227,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=20.0,
        replenishment_rate=20.0,
        metadata={"sector": "Disaster Relief Management"}
    ),
    Node(
        id="customer-vw",
        name="Saxony Metro Transit Operations",
        type=NodeType.PRODUCT,
        location="Wolfsburg, Germany",
        latitude=52.420,
        longitude=10.790,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=20.0,
        replenishment_rate=20.0,
        metadata={"sector": "Public Transport Grid"}
    ),

    # --- EXPANDED RESILIENCE NODES (Bringing total to 33 nodes) ---
    Node(
        id="supplier-singapore",
        name="Singapore Specialty Sourcing Partner",
        type=NodeType.SUPPLIER,
        location="Singapore",
        latitude=1.35,
        longitude=103.82,
        base_cost=14000.0,
        capacity=150.0,
        health=1.0,
        risk_score=0.0,
        inventory=300.0,
        safety_stock=100.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"material": "Specialized Solder Compounds", "partner_tier": 2}
    ),
    Node(
        id="port-singapore",
        name="Port of Singapore Global Hub",
        type=NodeType.PORT,
        location="Singapore",
        latitude=1.26,
        longitude=103.84,
        base_cost=28000.0,
        capacity=850.0,
        health=1.0,
        risk_score=0.0,
        inventory=300.0,
        safety_stock=100.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"terminal_ops": "Pasir Panjang Terminal"}
    ),
    Node(
        id="supplier-korea",
        name="Seoul Precision Chemical Partner",
        type=NodeType.SUPPLIER,
        location="Seoul, South Korea",
        latitude=37.56,
        longitude=126.97,
        base_cost=13500.0,
        capacity=160.0,
        health=1.0,
        risk_score=0.0,
        inventory=300.0,
        safety_stock=100.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"material": "Etching Components", "partner_tier": 2}
    ),
    Node(
        id="port-busan",
        name="Port of Busan Terminal",
        type=NodeType.PORT,
        location="Busan, South Korea",
        latitude=35.10,
        longitude=129.04,
        base_cost=24000.0,
        capacity=650.0,
        health=1.0,
        risk_score=0.0,
        inventory=300.0,
        safety_stock=80.0,
        daily_consumption=0.0,
        replenishment_rate=0.0,
        metadata={"terminal_ops": "Gamman Container Terminal"}
    ),
    Node(
        id="customer-water",
        name="Munich Clean Water Treatment Authority",
        type=NodeType.PRODUCT,
        location="Munich, Germany",
        latitude=48.14,
        longitude=11.59,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=10.0,
        replenishment_rate=10.0,
        metadata={"sector": "Critical Public Utilities"}
    ),
    Node(
        id="customer-power",
        name="Bavarian Energy Grid Operations",
        type=NodeType.PRODUCT,
        location="Munich, Germany",
        latitude=48.13,
        longitude=11.57,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=10.0,
        replenishment_rate=10.0,
        metadata={"sector": "Energy Distribution Grid"}
    ),
    Node(
        id="customer-transit",
        name="Munich Metropolitan Transit Authority",
        type=NodeType.PRODUCT,
        location="Munich, Germany",
        latitude=48.15,
        longitude=11.60,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=10.0,
        replenishment_rate=10.0,
        metadata={"sector": "Municipal Commuter Transit"}
    ),
    Node(
        id="customer-redcross",
        name="European Emergency Disaster Relief Depot",
        type=NodeType.PRODUCT,
        location="Munich, Germany",
        latitude=48.12,
        longitude=11.56,
        base_cost=0.0,
        capacity=500.0,
        health=1.0,
        risk_score=0.0,
        inventory=100.0,
        safety_stock=40.0,
        daily_consumption=10.0,
        replenishment_rate=10.0,
        metadata={"sector": "Emergency Disaster Relief Logistics"}
    )
]

# Seed edges representing flow routes (fully balanced)
SEED_EDGES: List[Edge] = [
    # --- PATH A LINKS (Main Chain) ---
    Edge(
        source="supplier-silicon",
        target="factory-wafer",
        type=EdgeType.SUPPLIES,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="factory-wafer",
        target="port-kaohsiung",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="port-kaohsiung",
        target="port-antwerp",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=5,
        transport_mode="ocean"
    ),
    Edge(
        source="port-kaohsiung",
        target="port-rotterdam",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.0,
        lead_time_days=6,
        transport_mode="ocean"
    ),
    Edge(
        source="port-antwerp",
        target="warehouse-munich",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=2,
        transport_mode="road"
    ),
    Edge(
        source="port-rotterdam",
        target="warehouse-munich",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.0,
        lead_time_days=2,
        transport_mode="road"
    ),
    Edge(
        source="warehouse-munich",
        target="factory-assembly",
        type=EdgeType.SUPPLIES,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="factory-assembly",
        target="distributor-europe",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="distributor-europe",
        target="product-nexus-ecu",
        type=EdgeType.MANUFACTURES,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),

    # --- PATH B LINKS (Stuttgart Chain) ---
    Edge(
        source="supplier-silicon-jp",
        target="factory-wafer-jp",
        type=EdgeType.SUPPLIES,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="factory-wafer-jp",
        target="port-yokohama",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="port-yokohama",
        target="port-hamburg",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=6,
        transport_mode="ocean"
    ),
    Edge(
        source="port-hamburg",
        target="warehouse-stuttgart",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=2,
        transport_mode="road"
    ),
    Edge(
        source="warehouse-stuttgart",
        target="factory-assembly-stuttgart",
        type=EdgeType.SUPPLIES,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="factory-assembly-stuttgart",
        target="distributor-europe-stuttgart",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="distributor-europe-stuttgart",
        target="product-nexus-ecu-pro",
        type=EdgeType.MANUFACTURES,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),

    # --- END RECIPIENT LINKS (B2B Deliveries) ---
    Edge(
        source="distributor-europe",
        target="customer-bmw",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.5,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="distributor-europe",
        target="customer-audi",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.5,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="distributor-europe-stuttgart",
        target="customer-mercedes",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.5,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="distributor-europe-stuttgart",
        target="customer-vw",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.5,
        lead_time_days=1,
        transport_mode="road"
    ),

    # --- EXPANDED EDGES (Linking Singapore, Busan and new community recipients) ---
    Edge(
        source="supplier-singapore",
        target="port-singapore",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="port-singapore",
        target="port-antwerp",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.0,
        lead_time_days=5,
        transport_mode="ocean"
    ),
    Edge(
        source="port-singapore",
        target="port-rotterdam",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.0,
        lead_time_days=5,
        transport_mode="ocean"
    ),
    Edge(
        source="supplier-korea",
        target="port-busan",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=1.0,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="port-busan",
        target="port-antwerp",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.0,
        lead_time_days=6,
        transport_mode="ocean"
    ),
    Edge(
        source="port-busan",
        target="port-rotterdam",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.0,
        lead_time_days=6,
        transport_mode="ocean"
    ),
    Edge(
        source="distributor-europe",
        target="customer-water",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.25,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="distributor-europe",
        target="customer-power",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.25,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="distributor-europe",
        target="customer-transit",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.25,
        lead_time_days=1,
        transport_mode="road"
    ),
    Edge(
        source="distributor-europe",
        target="customer-redcross",
        type=EdgeType.SHIPS_TO,
        dependency_ratio=0.25,
        lead_time_days=1,
        transport_mode="road"
    )
]
